version: '2' 

services:
  postgres:
    image: 'postgres:9.6-alpine'
    restart: unless-stopped
    environment:
      POSTGRES_USER: 'switchboard'
      POSTGRES_PASSWORD: 'M2gzYcKeeS8w21w7'
    ports:
      - '5432:5432'
    volumes:
      - 'postgres:/var/lib/postgresql/data'

volumes:
  postgres:

