# Generated by Django 4.0.6 on 2022-07-27 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0002_remove_service_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='accesstype',
            field=models.CharField(choices=[('order', 'Order'), ('openaccess', 'Open Access')], default='openaccess', max_length=10),
        ),
    ]
