# Generated by Django 4.0.6 on 2022-07-27 06:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('country', models.CharField(max_length=100)),
                ('website', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=250)),
                ('name', models.CharField(max_length=250)),
                ('description', models.TextField()),
                ('content', models.TextField()),
                ('accesstype', models.CharField(choices=[('order', 'Order'), ('openaccess', 'Open Acces')], default='openaccess', max_length=10)),
                ('slug', models.SlugField(max_length=250, unique_for_date='creationdate')),
                ('creationdate', models.DateTimeField(default=django.utils.timezone.now)),
                ('category', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='marketplace.category')),
                ('createdby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marketplace_services', to=settings.AUTH_USER_MODEL)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketplace.provider')),
            ],
            options={
                'ordering': ('-creationdate',),
            },
        ),
    ]
